#  IN ORDER TO RESET THE SETTINGS, JUUST WIPE THE ENTIRE FILE CONTENT Crtl+A, delete.
[general]
# Optional full override for the default project folder.
# macOS:
# default_project_path = "/Users/your_name/Projects"
# default_project_path = "/Volumes/ExternalSSD/Code"

# Linux:
# default_project_path = "/home/your_name/Projects"
# default_project_path = "/mnt/data/Code"

# Windows:
# is Preferred to write using forward slashes("/" the one Linux & macOS use):
#like "C:/Users/your_name/Projects" or "D:/Code"
# you mayuse single quotes if you want Windows backslashes: default_project_path = 'C:\Users\your_name\Projects'
# default_project_path = "~/Projects" is ok too "~" will be evalueted
default_project_path = "" # Leave empty to use: ~/default_projects_folder

# Folder name appended to the user's home directory when default_project_path is empty.
default_projects_folder = "Projects" # it means ~/Projects/. Empty means ~/. leave blank for None


[personal]
profile_name = "User"
grammatical_gender = "F" # soon
# Grammatical gender for localisation. Supported values: "F", "M", "X".
# Default fallback is "F". Used for basic string agreement instead of full pronoun mapping.
# NOTE: Certain localised strings may still exhibit minor grammatical mismatches.

language = "en" # defaults to enUK/Ca
enabled_greetings = true



[editors]
vscode_cmd           = "code {path}"
vscode_display       = "VSCode"
pycharm_cmd          = "pycharm {path}"
pycharm_display      = "PyCharm"
clion_cmd            = "clion {path}"
clion_display        = "CLion"
rider_cmd            = "rider {path}"
zed_cmd              = "zed {path}"
sublime_text_cmd     = "subl {path}"
sublime_text_display = "Sublime Text"
nvim_cmd             = "nvim {path}"
nvim_display         = "nVim"
intellij_cmd         = "idea {path}"
intellij_display     = "IntelliJ IDEA"
notepadpp_cmd        = "notepad++ {path}"
notepadpp_display    = "Notepad++"
godot_cmd            = "godot --path {path} -e"
godot_display        = "Godot's editor"
none_cmd             = "NOEDITOR"
none_display         = "None "
# To make yourself at home and add your own editors, just pop your details in like this:
# {editor_name}_cmd     = "your command here, remember to include {path}"
# {editor_name}_display = "A nice display name for it" (optional!)
# Just keep the {editor_name} part EXACTLY the same for both. It can literally be 'pineapplepizza'
# even if your editor is Eclipse. it’s just a variable, after all ! :) But I'd recommend keeping it
# clear, or it gets confusing fast (trust me on this one!). Happy coding! x
# keep in mind though that ReapySet can read your Zshrc or Bashrc if you use aliases


[python]
#General
disable_poetry_centralised_venvs = true

# package managers
default_pm                      = "PY:VENV" # PY:UV PY:VENV PY:POETRY PY:HATCH PY:CONDA PY:PIXI PY:MAMBA PY:PIPENV PY:VIRTUALENV PY:PDM
uv_path                         = ""
poetry_path                     = ""
hatch_path                      = ""
pdm_path                        = ""
pipenv_path                     = ""
virtualenv_path                 = ""
conda_path                      = ""
mamba_path                      = ""
pixi_path                       = ""



[js] # NOT IMPLEMENTED YET
default_runtime = "JS:NODE" # JS:NODE   JS:BUN JS:DENO JS:VANILLAJS
default_jspm = "JS:NPM" # JS:NPM JS:PNPM JS:BUN JS:YARN
typescript_by_default = true


[rust] # NOT IMPLEMENTED YET
cargo_path                      = ""   # placeholder

[dotnet] # NOT IMPLEMENTED YET
dotnetsdk_path                  = ""   # placeholder
default_unit_test_framework     = ""   # placeholder

[kotlin_java] # NOT IMPLEMENTED YET
gradle_path     = ""   # placeholder
maven_path      = ""   # placeholder

[go] # NOT IMPLEMENTED YET
go_path         = ""   # placeholder

[lua] # NOT IMPLEMENTED YET
lua_path        = ""   # placeholder




[advanced] # Avoid if you don't want to mess up with the Application
nativeMenubar = true # only macOS and some Linux DEs
main_window_height = 380 # on some linux distros or older windows versions or
# if you enable force_attached_menubar on macOS and gnome the window will get a bit clunky,
# i reccoment tweaking this value if you mess up with the menu bar or if your oprating system is very customised or not well detected by ReapySet
install_packages_on_project_creation = true # if you want to install the packages on project creation, set this to true.
# If you want to install them manually, set it to false. This is useful if you want to create a project without internet connection
# or if you want to install the packages later.:p