[general]
#soon


[personal]
profile_name = "User"
grammatical_gender = "F"
# Grammatical gender for localisation. Supported values: "F", "M", "X".
# Default fallback is "F". Used for basic string agreement instead of full pronoun mapping.
# NOTE: Certain localised strings may still exhibit minor grammatical mismatches.

language = "en" # defaults to enUK/Ca


[editors]
pycharm_cmd          = "pycharm {path}"
pycharm_display      = "PyCharm"
vscode_cmd           = "code {path}"
vscode_display       = "VSCode"
clion_cmd            = "clion {path}"
clion_display        = "CLion"
rider_cmd            = "rider {path}"
zed_cmd              = "zed {path}"
sublime_text_cmd     = "subl {path}"
sublime_text_display = "Sublime Text"
nvim_cmd             = "nvim {path}"
nvim_display         = "nVim"
intellij_cmd         = "idea {path}"
intellij_display     = "IntelliJ IDEA"
notepadpp_cmd        = "notepad++ {path}"
notepadpp_display    = "Notepad++"
godot_cmd            = "godot --path {path} -e"
godot_display        = "Godot's editor"
# To make yourself at home and add your own editors, just pop your details in like this:
# {editor_name}_cmd     = "your command here, remember to include {path}"
# {editor_name}_display = "A nice display name for it" (optional!)
# Just keep the {editor_name} part EXACTLY the same for both. It can literally be 'pineapplepizza'
# even if your editor is Eclipse — it’s just a variable, after all ! :) But I'd recommend keeping it
# clear, or it gets confusing fast (trust me on this one!). Happy coding! x


[python]
default_pm      = "PY:VENV" # PY:UV PY:VENV PY:POETRY PY:HATCH PY:GENERIC_CONDA PY:PIXI PY:MAMBA PY:PIPENV PY:VIRTUALENV PY:PDM
uv_path         = ""
poetry_path     = ""
hatch_path      = ""
pdm_path        = ""
pipenv_path     = ""
virtualenv_path = ""
conda_path      = ""
mamba_path      = ""
pixi_path       = ""

[rust]
cargo_path      = ""   # placeholder

[dotnet]
dotnet_path     = ""   # placeholder

[kotlin_java]
gradle_path     = ""   # placeholder
maven_path      = ""   # placeholder

[go]
go_path         = ""   # placeholder

[lua]
lua_path        = ""   # placeholder