
def populate_widget3(outcome: str):
    match outcome:
        case "PY":
            ...
        case "RUST":
            ...
        case "DOTNET":
            ...
        case "KT":
            ...
        case "CPP":
            ...
        case "TSJS":
            ...
        case "GO":
            ...
        case "LUA":
            ...
        case "GDScript":
            ...
        case _:
            ...